### PR TITLE
Fix chat messages sent twice

### LINKED ISSUE #460: Chat messages sent twice
**Which resource(s) have this problem?**
Playercolors

**Describe the bug**
Playercolors also has an event handler that listens to onPlayerChat, so every chat message is sent twice.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start playercolors and freeroam (Since 1.6, both start by default)
2. Send a message in the chat
3. See the message appear twice

**Expected behavior**
The message is sent only once.

**Screenshots**
image

**Version**
Client ver: Multi Theft Auto v1.6-release-22364
Client OS: Windows 11

Server ver:  MTA:SA Server v1.6-release-22361 (Latest nightly)
Server OS: Windows 11

**Additional context**
-

### PR DESCRIPTION
**Pull request by Fernando-A-Rocha**
Fixes #460 

playercolors will no longer handle chat, as this is handled in the gamemode resource itself (freeroam), playercolors is just an extra resource.

@Dark-Dragon @Nico8340

### CODE REVIEW

**Comment by Fernando-A-Rocha** [comment]
Other game modes that handle and output chat to chatbox are:
- TDM
- CTV
- Assault

Then, `admin` and `webstats` also handle onPlayerChat but don't alter its output.

**Comment by Dark-Dragon** [comment]
Appropriate fix for while we wait for the large scale changes discussed in #463

**Comment by Fernando-A-Rocha** [comment]
Exactly, this can be merged now.

File: [gameplay]/playercolors/playercolors.lua [hunk 1]
```diff
@@ -20,18 +20,5 @@ addEventHandler("onResourceStart", resourceRoot, setAllPlayerColors)
 addEventHandler("onGamemodeMapStart", root, setAllPlayerColors) -- mapmanager resets player colors to white when the map ends
 addEventHandler("onResourceStop", resourceRoot, setAllPlayerColors)
 
-addEventHandler('onPlayerChat', root,
-	function(msg, type)
-		if type == 0 then
```
Comment (jlillis) [inline [gameplay]/playercolors/playercolors.lua:25]: I think it would be better to just add an early return if `freeroam` is running, as this would break functionality on resources other than `freeroam`. Not that it's important functionality, I guess.

**Review by jlillis — CHANGES_REQUESTED** [review]

File: [gameplay]/playercolors/playercolors.lua (hunk 1 above)
Comment (Fernando-A-Rocha) [reply [gameplay]/playercolors/playercolors.lua:25]: I can't think of a reason you would need playercolors to handle chat for you, running alongside other resources... 🤔 To me, it's a bug that this PR fixes.

**Comment by Fernando-A-Rocha** [comment]
@jlillis do you agree with my comment above?

File: [gameplay]/playercolors/playercolors.lua (hunk 1 above)
Comment (jlillis) [reply [gameplay]/playercolors/playercolors.lua:25]: You would need it to if you expect the player's nametag colors to appear in chat in gamemodes other than `freeroam`.

Comment (Fernando-A-Rocha) [reply [gameplay]/playercolors/playercolors.lua:25]: > I think it would be better to just add an early return if `freeroam` is running, as this would break functionality on resources other than `freeroam`. Not that it's important functionality, I guess.

Ok

**Comment by Fernando-A-Rocha** [comment]
There you have it @jlillis

**Review by jlillis — APPROVED** [review]
